[project]
name = "gen-ai-stuffs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5",
    "crewai",
    "langchain_google_genai",
    "load_dotenv"
]
